name: Test Report

on:
  workflow_run:
    workflows: ['Continuous Integration & Delivery']
    types:
      - completed

jobs:
  report:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, windows-2022 ]

    runs-on: ubuntu-22.04

    permissions:
      actions: read
      checks: write
      contents: read

    steps:
      - name: Publish '${{ matrix.os }}' Test Report
        uses: dorny/test-reporter@v1
        with:
          artifact: ${{ matrix.os }}
          name: ${{ matrix.os }}
          path: '*.trx'
          reporter: dotnet-trx
